from __future__ import (  # Add this import at the top of the file for forward references
    annotations,
)

import copy
import json
import os
import shutil
from enum import Enum
from typing import List

import AsgardBench.utils as Utils
from AsgardBench import constants as c
from AsgardBench.goal import Goal
from AsgardBench.randomization import Randomization
from AsgardBench.setup import ObjectSetup, SetupAction
from AsgardBench.step import RawStep, Step


class PlanType(str, Enum):
    GENERATED = "generated"  # Plan generated algorithmically
    MODEL = "model"  # Plan generated by running a model
    REPLAY = "replay"  # Plan generated by replaying a previous plan
    MANUAL = "manual"  # Plan created manually by a user


class Plan:

    def __init__(self, steps: List[Step], raw_plan: RawPlan):

        self.name: str = raw_plan.name
        self.task_description: str = raw_plan.task_description
        self.scene = raw_plan.scene
        self.task_failed = raw_plan.task_failed
        self.steps: List[Step] = steps
        self.setup_actions: List[SetupAction] = raw_plan.setup_actions
        self.object_setup: ObjectSetup = raw_plan.object_setup
        self.randomization: Randomization = raw_plan.randomization
        self.plan_type: PlanType = raw_plan.plan_type
        self.goal: Goal = raw_plan.goal
        self.failed_steps: List[Step] = (
            raw_plan.failed_steps if raw_plan.failed_steps is not None else []
        )
        # For stripped plans without full steps array
        self._step_count: int | None = raw_plan._step_count
        self._initial_pose: dict | None = raw_plan._initial_pose

    @property
    def step_count(self) -> int:
        """Number of steps in the ground-truth plan."""
        if self._step_count is not None:
            return self._step_count
        return len(self.steps)

    @property
    def initial_pose(self) -> dict | None:
        """Initial agent pose from first step."""
        if self._initial_pose is not None:
            return self._initial_pose
        if self.steps:
            return self.steps[0].pose.to_dict()
        return None

    def to_dict(self):
        return {
            "name": self.name,
            "task_description": self.task_description,
            "scene": self.scene,
            "plan_type": self.plan_type.value,
            "task_failed": self.task_failed,
            "setup_actions": [action.to_dict() for action in self.setup_actions],
            "object_setup": self.object_setup.to_dict(),
            "goal": self.goal.to_dict(),
            "randomization": self.randomization.to_dict(),
            "steps": [step.to_dict() for step in self.steps],
            "failed_steps": [step.to_dict() for step in self.failed_steps],
        }

    @classmethod
    def from_dict(cls, data: dict) -> Plan:
        # Support both full and stripped plan formats
        if "steps" in data:
            steps = [Step.from_dict(step) for step in data["steps"]]
            step_count = None
            initial_pose = None
        else:
            # Stripped format - no steps array
            steps = []
            step_count = data.get("step_count")
            initial_pose = data.get("initial_pose")

        return Plan(
            steps,
            RawPlan(
                task_description=data["task_description"],
                name=data["name"],
                first_step=None,  # first_step is not used in Plan
                scene=data["scene"],
                randomization=Randomization.from_dict(data["randomization"]),
                plan_type=PlanType(data["plan_type"]),
                setup_actions=[
                    SetupAction.from_dict(action)
                    for action in data.get("setup_actions", [])
                ],
                object_setup=ObjectSetup.from_dict(data.get("object_setup", {})),
                goal=Goal.from_dict(data.get("goal", {})),
                failed_steps=[
                    Step.from_dict(step) for step in data.get("failed_steps", [])
                ],
                step_count=step_count,
                initial_pose=initial_pose,
            ),
        )

    def task_type(self):
        # Task type is everything before "FloorPlan" in the name
        return self.name.split("FloorPlan")[0].strip()

    def make_failed_plans(self, max_plans: int, source_dir: str):
        """
        Create failed plans from the steps in the plan.
        If a step has a failed action, create a new plan with that action injected.
        """
        for i, failed_step in enumerate(self.failed_steps):
            if i >= max_plans:
                Utils.print_color(
                    c.Color.YELLOW, f"Max failed plans reached: {max_plans}"
                )
                break
            self.make_failed_plan(failed_step, i, source_dir)

        # Remove FAIL items from original plan
        for filename in os.listdir(source_dir):
            full_file_name = os.path.join(source_dir, filename)

            if filename.endswith(".png") and "FAIL" in filename:
                os.remove(full_file_name)

    def make_failed_plan(self, failed_step: Step, index: int, source_dir: str):
        """
        If plan saves a failed step, I can make a copy with
        the failed step injected into the plan.
        This is useful for training failure recovery.
        """

        # If plan already has an error injection, skip
        if self.randomization.error_injection is not None:
            return

        # Failed step may no longer be valid after plan created and step consolidated
        if failed_step.image_filename.startswith("_"):
            return

        # Extract step number from the failed step image filename
        # (i.e. 2_pickup pot.png -> 2)
        step_number = Utils.get_image_index(failed_step.image_filename)

        if step_number >= len(self.steps) - 1:
            Utils.print_color(
                c.Color.YELLOW,
                f"MakeFailedPlan: Step number {step_number} is out of range for plan with {len(self.steps)} steps",
            )
            return

        failed_step = copy.deepcopy(failed_step)

        # Extact the action from the failed step
        # (i.e. _2_pickup pot.png -> pickup pot)
        action = failed_step.image_filename.split("_")[1]

        # Create a new direcory name
        # put_away_Dishes_clean_FloorPlan29_V1-Bowl Pot [15] -> put_away_Dishes_clean_FloorPlan29_V1F_pickup pot fail_R-Bowl Pot [15]
        # Extact code before the "-" or "[" if ther is no "-"
        if "-" in self.name:
            parts = self.name.split("-")
            # Get last part
            base_name = parts[-2]
            tail = f"-{parts[-1]}"
        elif "[" in self.name:
            base_name = source_dir.split("[")[0]
            tail = ""
        else:
            base_name = self.name
            tail = ""

        # Get all but last part of the source_dir
        source_base = os.path.dirname(source_dir)

        new_name = f"{base_name}F{index}_{action}{tail}"
        new_dir = f"{source_base}/{new_name}"

        # Copy all the files from the source_dir to the new_dir
        if not os.path.exists(new_dir):
            os.makedirs(new_dir)
        for filename in os.listdir(source_dir):
            full_file_name = os.path.join(source_dir, filename)

            # Only copy images after and including the "FAIL" image
            if filename.endswith(".png") and not "FAIL" in filename:
                index = Utils.get_image_index(filename)
                if index <= step_number:
                    continue

            # Skip if additional FAIL image later in plan
            if filename.endswith(".png") and "FAIL" in filename:
                index = Utils.get_image_index(filename)
                if index != step_number:
                    continue

            if os.path.isfile(full_file_name):
                shutil.copyfile(full_file_name, os.path.join(new_dir, os.path.basename(full_file_name)))

        # Create a copy of the plan
        fail_plan = copy.deepcopy(self)
        fail_plan.name = new_name

        # Remove the first "step_number" steps from the plan
        fail_plan.steps = fail_plan.steps[(step_number + 1) :]
        fail_plan.randomization.fail_action = failed_step.action_desc

        # Copy data from new first step to fail step
        failed_step.history = copy.deepcopy(fail_plan.steps[0].history)
        failed_step.object_bounding_boxes = copy.deepcopy(
            fail_plan.steps[0].object_bounding_boxes
        )
        failed_step.updated_memory = copy.deepcopy(fail_plan.steps[0].updated_memory)
        failed_step.observations = copy.deepcopy(fail_plan.steps[0].observations)

        # Add fail observation to the first step
        fail_plan.steps[0].observations.append(
            f"I was unable to {failed_step.action_desc}"
        )

        # Add failed action to history of all steps
        insert_index = len(fail_plan.steps[0].history)
        for step in fail_plan.steps:
            step.history.insert(insert_index, failed_step.action_desc)

        # Add the failed step to the beginning of the steps
        fail_plan.steps.insert(0, failed_step)

        # Save the plan
        # Save json version of action plan
        filename = f"{new_dir}/plan.json"
        with open(filename, "w") as file:
            json.dump(fail_plan.to_dict(), file)

        # Add step count to end of dir
        step_dir = f"{new_dir} [{len(fail_plan.steps)}]"
        os.rename(new_dir, step_dir)

        Utils.print_color(c.Color.GREEN, f"Created failed plan in {step_dir}")

        return fail_plan


class RawPlan:
    """
    Represents a raw plan containing a sequence of steps to be executed.
    """

    def __init__(
        self,
        task_description: str,
        name: str,
        first_step: RawStep,
        scene: str,
        setup_actions: List[SetupAction],
        object_setup: ObjectSetup,
        randomization: Randomization,
        plan_type: PlanType,
        goal: Goal = None,
        failed_steps: List[Step] = None,
        step_count: int = None,
        initial_pose: dict = None,
    ):
        self.name = name
        self.task_description = task_description
        self.scene = scene
        self.task_failed = False
        self.setup_actions = setup_actions
        self.object_setup = object_setup
        self.randomization = randomization
        self.plan_type = plan_type
        self.goal = goal if goal is not None else Goal()

        self.first_step = first_step

        # List of saved failed steps
        self.failed_steps = failed_steps if failed_steps is not None else []

        # For stripped plans without full steps array
        self._step_count = step_count
        self._initial_pose = initial_pose

    def to_dict(self):
        return {
            "task_description": self.task_description,
            "name": self.name,
            "scene": self.scene,
            "setup_actions": [action.to_dict() for action in self.setup_actions],
            "object_setup": self.object_setup.to_dict(),
            "randomization": self.randomization.to_dict(),
            "plan_type": self.plan_type.value,
            "goal": self.goal.to_dict(),
            "task_failed": self.task_failed,
            "step_count": self.step_count(),
            "step": self.first_step.to_dict(),
            "failed_steps": [step.to_dict() for step in self.failed_steps],
        }

    @classmethod
    def from_dict(cls, data: dict) -> RawPlan:
        first_step = RawStep.from_dict(data["step"])
        plan = cls(
            task_description=data["task_description"],
            name=data["name"],
            first_step=first_step,
            scene=data["scene"],
            setup_actions=[
                SetupAction.from_dict(action)
                for action in data.get("setup_actions", [])
            ],
            object_setup=ObjectSetup.from_dict(data.get("object_setup", {})),
            randomization=Randomization.from_dict(data["randomization"]),
            plan_type=PlanType(data["plan_type"]),
            goal=Goal.from_dict(data.get("goal", {})),
            failed_steps=[
                Step.from_dict(step) for step in data.get("failed_steps", [])
            ],
        )

        plan.link_parent_ids()
        return plan

    def link_parent_ids(self):
        # Create a dictionary to map step IDs to Step objects
        step_map = {self.first_step.id: self.first_step}

        def traverse(step: RawStep):
            for substep in step.substeps:
                step_map[substep.id] = substep
                traverse(substep)

        traverse(self.first_step)

        # Link parent IDs
        def link_parents(step: RawStep):
            if step.parent_id:
                step.parent = step_map.get(step.parent_id)
            for substep in step.substeps:
                link_parents(substep)

        link_parents(self.first_step)

    def step_count(self):
        if self._step_count is not None:
            return self._step_count
        return self.first_step.step_count()

    def initial_pose(self):
        if self._initial_pose is not None:
            return self._initial_pose
        # Could extract from first_step if needed
        return None

    def plan_from_raw_plan(self, save_dir: str) -> Plan:
        """
        Convert the raw_plan to flat Plan
        Only include steps with an _image_filename.
        The reasoning for each step is the aggregate of the reasoning
        for all ancestor steps (including itself) that do not have an _image_filename.
        """
        steps: List[Step] = []
        history: List[str] = []

        def collect_reasoning(raw_step: RawStep):
            reasoning = [raw_step.reasoning]
            current: RawStep = raw_step
            while current:
                if current.image_filename() is None and current.reasoning:
                    reasoning.insert(0, current.reasoning)
                current = current.parent
            return reasoning

        def collect_task_description(raw_step: RawStep):
            current: RawStep = raw_step.parent
            while current:
                if current.parent is None:
                    return current.action_desc
                elif current.image_filename() is None:
                    current = current.parent
                else:
                    return current.action_desc
            return "NONE"

        def get_memories(raw_step: RawStep):
            if raw_step.memory is None or len(raw_step.memory) == 0:
                return []

            memories: List[str] = []
            for memory in raw_step.memory.values():
                mems = memory.to_string()
                memories.extend(mems)
            return memories

        def traverse(raw_step: RawStep):
            # if raw_step.image_filename() is not None:
            # if not raw_step.is_injection: TEMPTEMP
            reasoning = collect_reasoning(raw_step)
            task_description = collect_task_description(raw_step)
            updated_memory = get_memories(raw_step)

            step = Step(
                action_desc=raw_step.action_desc,
                task_description=task_description,
                action=raw_step.action,
                obj=raw_step.object,
                observations=raw_step.observations,
                updated_memory=updated_memory,
                object_bounding_boxes=raw_step.object_bounding_boxes,
                pose=raw_step.pose,
                reasoning=reasoning,
                filename=raw_step.image_filename(),
                history=history.copy(),
            )

            # If actual action step add to history
            if step.image_filename is not None:
                history.append(raw_step.action_desc)

            # If an injection clear any image
            if raw_step.is_injection:
                step.image_filename = None

            steps.append(step)

            for substep in raw_step.substeps:
                traverse(substep)

        traverse(self.first_step)

        # Now set last_memory on each action to the memory of the previous action
        for i in range(1, len(steps)):
            steps[i].memory = steps[i - 1].updated_memory

        # Remove all steps without an image_filename
        steps = [step for step in steps if step.image_filename is not None]

        action_plan = Plan(steps, self)

        # Now clean up the image file numbering as not all are used
        for i, step in enumerate(action_plan.steps):
            old_index = Utils.get_image_index(step.image_filename)
            old_filepath = os.path.join(save_dir, step.image_filename)
            new_filename = Utils.set_image_index(step.image_filename, i)
            step.image_filename = new_filename
            # Rename the file
            new_filepath = os.path.join(save_dir, new_filename)
            os.rename(old_filepath, new_filepath)

            # Find all image files with c.FAIL in the name
            for filename in os.listdir(save_dir):
                if filename.startswith(f"_{old_index}_") and c.FAIL in filename:
                    new_fail_filename = filename.replace(f"_{old_index}_", f"{i-1}_")
                    os.rename(
                        os.path.join(save_dir, filename),
                        os.path.join(save_dir, new_fail_filename),
                    )

                    # Update the failed step's image filename if it matches
                    for step in action_plan.failed_steps:
                        if step.image_filename == filename:
                            step.image_filename = new_fail_filename

        # Delete any unused images
        for filename in os.listdir(save_dir):
            if filename.startswith("_") and filename.endswith(".png"):
                os.remove(os.path.join(save_dir, filename))

        return action_plan
